spring:
  application:
    name: ms-digital-library-book-store-producer
 

server:
  port: 8085

# Apache Kafka #
custom:
  kafka:
    bootstrap-servers: localhost:9092
    topic-name: topic-book #Cola
    group-id: group-id

# Registry Client

#eureka:
#   client:
#      fetch-registry: true
#      serviceUrl:
#         defaultZone: http://localhost:8889/eureka

# Actuator
# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"

#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true   
  endpoints:
      web:
        exposure:
          include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

#keycloak:
#  realm: realm-proyecto
#  auth-server-url: http://localhost:8080/
#  resource: springboot-keycloak.
#  use-resource-role-mappings: false
#  public-client: true
#  bearer-only: true