server:
  port: 8888
spring:
  application:
    name: ms-digital-library-cloud-server-config
#  Configuracion Local
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///D:/desarrollo-fullstack/backend-java/workspace_sts/proyecto-galaxyv2/ms-digital-library-cloud-config-data



#  #Configuracion Cloud (git)
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/msvictorkevin-code/ms-digital-library-cloud-config-repo.git
#          search-paths:
#            - ms-digital-library-cloud-config-repo
#          username: ${USER_NAME}
#          password: ${USER_PASSWORD}
#          clone-on-start: true
#          force-pull: true
#          timeout: 5
#          default-label: main
